name: Deploy Components

on:
  workflow_dispatch:
    
jobs:
  deploy-components:
    name: "Deploy Components"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform/proxmox

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Ensure Inventory Directory Exists
        run: mkdir -p ../../ansible/inventory

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -no-color

      - name: Generate Inventory
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          TF_VAR_ssh_keys: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -target=local_file.ansible_inventory -auto-approve -no-color

      - name: Create SSH Key File
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Fetch Kubeconfig
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory/hosts.yml --private-key ~/.ssh/id_rsa -b -v fetch-kubeconfig.yml

      - name: Deploy K8s Components
        working-directory: ./
        run: |
          export KUBECONFIG=ansible/inventory/artifacts/admin.conf
          kubectl get nodes

          # Deploy MetalLB LoadBalancer
          kubectl apply -f kubernetes/metallb/
          
    #       # Deploy Ingress-Nginx
    #       kubectl apply -f kubernetes/ingress-nginx/
          
    #       # Deploy Local Path Provisioner
    #       kubectl apply -f kubernetes/rancher-local/
          
    #       # Deploy Rook Ceph
    #       kubectl apply -f kubernetes/rook-ceph/crds.yaml
    #       kubectl apply -f kubernetes/rook-ceph/common.yaml
    #       kubectl apply -f kubernetes/rook-ceph/operator.yaml
    #       kubectl wait --for=condition=Available deployment/rook-ceph-operator -n rook-ceph --timeout=120s
    #       kubectl apply -f kubernetes/rook-ceph/cluster.yaml
          
    #       # Deploy Cert-Manager
    #       kubectl apply -f kubernetes/cert-manager/cert-manager.yaml
    #       kubectl wait --for=condition=Available deployment/cert-manager-webhook -n cert-manager --timeout=120s
          
    #       # Create Cloudflare Secret & Apply Cluster Issuers
    #       sed "s/CLOUDFLARE_API_TOKEN/${{ secrets.CLOUDFLARE_API_TOKEN }}/g" kubernetes/cert-manager/cluster-issuers.yaml | kubectl apply -f -

    #   - name: Setup Helm
    #     uses: azure/setup-helm@v4.2.0

    #   - name: Deploy Monitoring Stack
    #     run: |
    #       helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    #       helm repo update
    #       export KUBECONFIG=ansible/inventory/artifacts/admin.conf
    #       helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
    #         --namespace monitoring \
    #         --create-namespace \
    #         -f kubernetes/monitoring/values.yaml
          
    #   - name: Deploy Logging Stack
    #     run: |
    #       helm repo add grafana https://grafana.github.io/helm-charts
    #       helm repo update
    #       export KUBECONFIG=ansible/inventory/artifacts/admin.conf
    #       helm upgrade --install loki-stack grafana/loki-stack \
    #         --namespace logging \
    #         --create-namespace \
    #         -f kubernetes/logging/values.yaml
