name: Destroy Infrastructure

on:
  workflow_dispatch:
  push:
    
jobs:
  terraform:
    name: "Destroy Infrastructure"
    runs-on:
      group: kloudke
    defaults:
      run:
        working-directory: ./terraform/proxmox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Inventory Directory Exists
        run: mkdir -p ../../ansible/inventory

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Destroy
        id: plan
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          TF_VAR_ssh_keys: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform destroy -input=false -no-color --auto-approve
