name: Provision Infrastructure

on:
  workflow_dispatch:
  push:
  #  branches:
  #    - main
  #    - master

jobs:
  terraform:
    name: "Terraform Provision"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform/proxmox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Inventory Directory Exists
        run: mkdir -p ../../ansible/kubespray/inventory

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          TF_VAR_ssh_keys: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          TF_VAR_ssh_keys: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -input=false -no-color --auto-approve -parallelism=1

      - name: Upload Ansible Inventory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: ansible/kubespray/inventory/hosts.yml
